/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconStar: typeof import('./src/components/icons/IconStar.vue')['default']
    IconStarOutline: typeof import('./src/components/icons/IconStarOutline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeatherCard: typeof import('./src/components/weather-card/weatherCard.vue')['default']
  }
}
